### ISSUE TITLE
Live reloading

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1207]
Support for live restart.

## PoC

- [x] Investigate Quarkus like live reloading
- [x] Investigate Micronaut like live restarting
- [x] Understand Gradle well enough to make design decisions
- [x] Create build loop implementation that can perform full and incremental builds (Maven only)
- [x] Add application lifecycle mechanism (start/restart/stop)
- [x] Create dev loop using build loop and app lifecycle.
- [x] Support binaries only mode (assumes external tool/IDE doing builds)
- [x] Add Helidon support to shutdown cleanly (close sockets) on some signal.

### Maven

- [ ] Support full Maven effective pom configuration

### Gradle

- [ ] Create Gradle task(s) to start / stop server on build start / complete
