### ISSUE TITLE
Generating minimal Java runtime

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1208]
## Helidon

- [x] SE/MP support to force exit once app is started (`-Dexit.on.started=!`)
- [x] Once we have a build-tools release:
  - [x] `java-image` maven profile to produce the custom JRI
  - [x] `Dockerfile.java` to produce a docker image containing only a custom JRI
  - [x] Document use of `java-image`

### Linker

- [x] Simple logging API to support both Maven and non Maven use cases
- [x] Default `System.out` log implementation
- [x] Config builder
- [x] Command line config parsing
- [x] Java Runtime parsing
- [x] Application parsing
- [x] Process monitoring
- [x] JDK dependency collection, using `jdeps` or `module-info.class` if present
- [x] JRI creation using `jlink`
- [x] Install app jars into JRI
- [x] Collect app startup class list
- [x] Generate CDS archive
- [x] Generate bash `start` script for non-Windows, customized by config
- [x] Generate powershell `start` script for Windows, customized by config
- [x] Add a help message if powershell script execution fails due to execution policy
- [x] Test image by running `start --test` 
- [x] Compute and display sizes
- [x] Fail if JDK 9 and CDS is enabled in a docker build since it will fail at runtime
- [ ] Release build-tools

### Maven plugin

- [x] Wire maven log to linker log
- [x] Support all linker configuration options
- [x] Use linker to produce image
