### ISSUE TITLE
Jenkins based build pipelines

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1210]
Support for

- [x] create a "publisher" webapp to publish results for the community
  - [x] Jenkins plugin to publish the results
  - [x] Jenkins SCM trait to customize the GH commit status links
  - [x] Webapp backend to store results
  - [x] Webapp frontend to view the results 
  - [x] Deploy the webapp on OKE and expose it to https://builds.helidon.io 
- [x] Setup a k8s cluster based CI infrastructure
  - [x] Jenkins k8s deployment
    - [x] Docker image with configurations and plugins
    - [x] K8s deployment with backups
- [x] Convert the existing wercker pipeline to a Jenkins pipeline
- [x] Add support for multiple java versions (> 11)
- [ ] Add support for Mac and Windows
- [ ] Native-image integration tests

**Comment by m0mus** [comment]
@romain-grecourt please add tracking check boxes to the issue

**Comment by romain-grecourt** [comment]
done.
