### ISSUE TITLE
Configuration changes for 2.0

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1211]
Epic for configuration changes

- [x] Refactor polling strategies #577 
- [x] Refactor change support #579 
- [x] Follow up - post change support #1183 
- [x] Service loader changes #1212
- [x] File type detectors change #1213 
- [x] All sources on classpath #1214
- [x] Polling strategy replanning #255 
- [x] API should not return `null` #1333

**Comment by tomas-langer** [comment]
- [ ] Refactor polling strategies #577 
- [ ] Refactor change support #579 
- [ ] Follow up - post change support #1183 
- [ ] Service loader changes #1212
