### ISSUE TITLE
2.0 Smaller changes

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1216]
This is an epic to track changes for 2.0 that do not deserve their own epic.

- [x] Helidon Features #1215 
- [x] Upgrade Weld #1152 
- [x] Upgrade OpenTracing #706 
- [x] Move to Jakarta libraries instead of `javax`, still use `javax` packages #1151 
- [x] Remove `valve` #514 
- [x] Update to Java 11 APIs #1220 
- [x] Javadoc fix #1223 

Security:
- [x] OIDC provider scope & audience #647 
- [x] Remove entity modification support #1219 

Removed from 2.0 scope:
- Revisit all JWT related providers #478 (deprecate in 2.0, mark for 3.x)

**Comment by tomas-langer** [comment]
- [ ] Helidon Features #1215 
- [ ] Upgrade Weld #1152 
- [ ] Upgrade OpenTracing #706 
- [ ] Move to Jakarta libraries instead of `javax`, still use `javax` packages #1151 
- [ ] Remove `valve` #514 

Security:
- [ ] OIDC provider scope & audience #647 
- [ ] Revisit all JWT related providers #478

**Comment by romain-grecourt** [comment]
How about:

- Improved `Single` (add a `CompletionStage` feeling)
- Improved `Multi` (add a `java.util.Stream` feeling)
- Add a `Limiter` interface to `io.common.reactive` to use with `Multi.limit`
- Add a `Multi.mapMany` to support flat mapping with `Multi`
- Add a back pressure base processor
- Add support for virtual byte buffers and virtual data chunks to support media streaming
- Add a line splitting processor

Some of these items may deserve their own epic or need to be discussed.

**Comment by danielkec** [comment]
> How about:
> 
> * Improved `Single` (add a `CompletionStage` feeling)
> * Improved `Multi` (add a `java.util.Stream` feeling)
> * Add a `Limiter` interface to `io.common.reactive` to use with `Multi.limit`
> * Add a `Multi.mapMany` to support flat mapping with `Multi`
> * Add a back pressure base processor
> * Add support for virtual byte buffers and virtual data chunks to support media streaming
> * Add a line splitting processor
> 
> Some of these items may deserve their own epic or need to be discussed.

I have moved all additional processors created for RS to common-reactive module and added them to the `Multi` interface, flatMap and limit are among them https://github.com/oracle/helidon/pull/1148/commits/56c995f53d569c691a04fcd81505afa799a4a28e

I used in the Multi same operator names as in RS, but can change them if there is some convention I didn't follow.
