### ISSUE TITLE
WebServer changes for 2.0

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1217]
Epic for WebServer changes

- [x] Socket configuration #929 
- [x] Exception writer #878 
- [x] Content API #820 
- [x] Programmatic API for SSL #592 
- [x] Refactor server configuration #575 
- [x] Consistent property naming #453 (seems to be duplicate of #575 )
- [x] Update WebServer APIs to use `Single` and `Multi` #1868

Postponed:
 System services #780 - requires proper design. The current approach is usable. Rather than doing it wrong, we have decided to postpone after 2.0 release

**Comment by romain-grecourt** [comment]
How about:

- Routing abstraction (grpc, websocket, http2)
- Request re-routing (e.g. `ServerRequest.route(String)`) ; this can be used to implement smart reverse proxies ; (useful for javascript single page apps) ; can open a lot of use-cases
- Fluent path params processing (Using optionals instead of plain types)
- Use of `Mappable` instead of Optional for query parameters and path parameters. (`Mappable` to be extracted from config)
- Re-worked media API (see HTTP client and MultiPart features)
- Use of Single instead of `CompletionStage` (improve `Single` to give it a `CompletionStage` feeling)
- Use of Multi instead of Publisher: make `Content` extend `Multi<DataChunk>` instead of `Publisher<DataChunk>` (improve `Multi` to give it a `java.util.Stream` feeling)
- Streamable media support based on streaming parsers (E.g. MultiPart, XML, JSON etc.)
- Move the static content support to a separate module and Implement directory listing (maps to a feature as well)
- Improved error handling so that media support can handle their own exception, also provide an way to register error handlers with `Routing.Rules`)

Or also:
- Better unit testing support
- OpenAPI binding: create generic endpoints from an OpenAPI descriptor and bind business logic ; this could be done with build time code generation or at runtime either with a little bit of reflection or with a mapping for the bindings implemented by the user.

A lot of these may deserve their own epic or need to be discussed.
