### ISSUE TITLE
Support WebSocket

### ISSUE THREAD

**Issue by dansiviter** [oracle/helidon#1231]
Tasks:

- [x] Integrate TyrusSupport POC implementation (SE) #1283
- [x] Basic messaging including encoders and decoders (SE) #1284
- [x] Integration into Helidon MP
- [x] Path mapping and `@RoutingName/@RoutingPath`
- [x] Configuration and Handshakes
- [x] Examples for SE and MP
- [x] Basic documentation
- [x] Executor services in MP

POC Wiki:

https://github.com/oracle/helidon/wiki/WebSockets-Support:-Tyrus-Integration

**Comment by spericas** [comment]
Current plan is to add WebSocket support in Helidon 2.0.

**Comment by dansiviter** [comment]
Great. I didn't see it on the 'Helidon 2.0' project board so I was concerned it had been dropped.

We'd like to use this to have low-latency bi-directional and super-small binaries. So I suppose I'm saying we'd also like CDI integration and Graal compatibility too. :)

**Comment by m0mus** [comment]
Added to 2.0 milestone and to the board. @spericas please add status status tracking checkboxes if needed.

**Comment by spericas** [comment]
Tasks:

- [ ] Integrate TyrusSupport POC implementation (SE)
- [ ] Basic messaging including encoders and decoders (SE)
- [ ] Integration into Helidon MP
- [ ] Path mapping
- [ ] Sessions
- [ ] Configuration and Handshakes
- [ ] Security
- [ ] Advanced messaging

POC Wiki: 

https://github.com/oracle/helidon/wiki/WebSockets-Support:-Tyrus-Integration

**Comment by spericas** [comment]
Will move security, tracing, etc to another issue.
