### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#1419]
Update examples:

MP:

- [x] only use `META-INF/microprofile-config.properties` and `application.yaml` on the classpath for MP
- [x] Remove setup of `logging.properties`, done automatically now - PR #2583 
- [x] Remove `Main` classes unless they do something important (and use `io.helidon.microprofile.cdi.Main` as the main class)
- [x] Remove application classes unless they are significant (e.g. add `@ApplicationPath` that diffes from `/`)
- [x] Use `${key}` instead of `'{ALIAS=key}` in all examples - PR #2579 

SE:

- [x] Use Helidon WebClient for tests and examples

**Comment by barchetta** [comment]
Some of this addressed by PR #1715
