### ISSUE TITLE
More reactive operators (tracking issue)

### ISSUE THREAD

**Issue by akarnokd** [oracle/helidon#1500]
Proposed operators:

- [x] `Multi.defaultIfEmpty(T)` (#1520)
- [x] `Multi.defer(Supplier)` (#1503)
- [x] `Multi.from(CompletionStage)` (#1511)
- [x] `Multi.from(Stream)` (#1525)
- [x] `Multi.interval()` (#1526)
- [x] `Multi.observeOn` (#1546)
- [x] `Multi.reduce(BiFunction)` (#1504)
- [x] `Multi.reduce(Supplier, BiFunction)` (#1504)
- [x] `Multi.retry(long)` (#1541)
- [x] `Multi.retry(BiPredicate<Throwable, Long>)` (#1541)
- [x] `Multi.retryWhen(BiFunction<Throwable, Long, Publisher>)` (#1541)
- [x] `Multi.switchIfEmpty(Publisher)` (#1527)
- [x] ~~`Multi.takeUntil(CompletionStage)`~~ decided not to have a dedicated operator for this
- [x] `Multi.takeUntil(Publisher)` (#1502)
- [x] `Multi.timeout()` (#1532)
- [x] `Multi.timer()` (#1516)

---------------

- [x] `Single.defaultIfEmpty(T)` (#1520)
- [x] `Single.defer(Supplier)` (#1503)
- [x] `Single.flatMapIterable(Function)` (#1517)
- [x] `Single.from(CompletionStage)` (#1511)
- [x] `Single.observeOn` (#1546)
- [x] `Single.retry(long)` (#1541)
- [x] `Single.retry(BiPredicate<Throwable, Long>)` (#1541)
- [x] `Single.retryWhen(BiFunction<Throwable, Long, Publisher>)` (#1541)
- [x] `Single.switchIfEmpty(Single)` (#1527)
- [x] ~~`Single.takeUntil(CompletionStage)`~~ decided not to have a dedicated operator for this
- [x] `Single.takeUntil(Publisher)` (#1502)
- [x] `Single.timer()` (#1516)
- [x] `Single.timeout()` (#1532)

**Comment by akarnokd** [comment]
Done.
