### ISSUE TITLE
Helidon CLI using Maven

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1506]
List of tasks for Maven support:

- [X] Implement development loop
- [X] Create Maven extension to extract project information 
- [X] Design and implement CLI harness
- [X] Integrate CLI harness with dev loop
- [X] Init command using archetypes
- [X] Dev command
- [X] Build command
- [X] Info command
- [X] Version command
- [X] Feature command from properties file
- [x] Unit testing
- [x] Verify compilation under Graal native
- [x] JLink support in build command
- [x] Native support in build command

**Comment by spericas** [comment]
New epic #1506 for next milestone opened.
