### ISSUE TITLE
Documentation for Helidon (Master Epic)

### ISSUE THREAD

**Issue by m0mus** [oracle/helidon#1515]
This epic collects all documentation task for Helidon 2.0.

- [x] Refactor documentation structure. Separate Helidon SE and Helidon MP docs. [1514](https://github.com/oracle/helidon/pull/1514)
- [x] Create Under Construction statement for documentation that is incomplete. [1586](https://github.com/oracle/helidon/pull/1586)

**About**

- [x] Introduction [1625](https://github.com/oracle/helidon/issues/1625)  
  - [x] Helidon purpose in general
  - [x] Helidon goals
  - [x] More about 2 flavors of Helidon
  - [x] Differences between SE and MP
- [x] Guides
  - [x] Restructure Guides page. Separate SE and MP guides.
  - [x] Guide for DB Client [206](https://github.com/oracle/helidon/issues/206)
  - [x] Guide for Web Client [1627](https://github.com/oracle/helidon/issues/1627)
  - [x] Guide for using static context (#1654)
  - [x] Change page names with SE or MP prefix to get it sorted in the TOC panel

**SE**

- [x] Introduction to Helidon SE 2.0 [1626](https://github.com/oracle/helidon/issues/1626)
  - [x] Nice image with components (from slides) or cards [2173](https://github.com/oracle/helidon/issues/2173)
  - [x] Update components list, add links
- [x] Config
  - [x] Reflect Helidon 2.0 changes ----- get updated doc status from Tomas
  - [x] Additional changes for Config 2.0
- [x] DB Client [1629](https://github.com/oracle/helidon/issues/1629)
  - [x] **Write docs**
- [x] gRPC Server
  - [x] Reflect Helidon 2.0 changes (if any)
- [x] Health Checks
  - [x] Reflect Helidon 2.0 changes (if any)
- [ ] Metrics [2196](https://github.com/oracle/helidon/issues/2196)
  - [ ] Reflect Helidon 2.0 changes (if any)
  - [ ] Cover more use cases.
- [ ] OpenAPI https://github.com/oracle/helidon/issues/2199
  - [ ] Reflect Helidon 2.0 changes (if any)
  - [ ] Cover more use cases.
- [x] Reactive Web Server
  - [ ] Reflect Helidon 2.0 changes (if any)
- [x] Reactive Messaging [1483](https://github.com/oracle/helidon/pull/1483)
- [x] Reactive Streams
- [ ] Security https://github.com/oracle/helidon/issues/2203
  - [ ] Reflect Helidon 2.0 changes (if any)
- [ ] Tracing
  - [ ] Reflect Helidon 2.0 changes (if any)
- [x] Web Client [1630](https://github.com/oracle/helidon/issues/1630)
  - [x] **Write docs**
  - [ ] Updates for Web Client doc [1862](https://github.com/oracle/helidon/pull/1862) 
- [x] Websocket [1631](https://github.com/oracle/helidon/pull/1631) Santiago
  - [x] **Write docs**
- [x] Cross Origin Resource Sharing (CORS) support

**MP**

- [x] Introduction to Helidon MP 2.0 [1628](https://github.com/oracle/helidon/issues/1628)
  - [x] Nice image with components (from slides) or cards [2172](https://github.com/oracle/helidon/issues/2172)
  - [x] Update components list, add links
- [ ] Config ---- get updated doc status from Tomas. 
  - [x] About MP Config specification
  - [ ] Concepts
  - [ ] How it's related to Helidon SE Config (partially covered in JAX-RS)
  - [ ] Use cases 
- [ ] CDI Extensions https://github.com/oracle/helidon/issues/2202
  - [ ] Reflect Helidon 2.0 changes (if any)
- [x] gRPC Server
  - [x] Reflect Helidon 2.0 changes (if any)
- [x] Health Checks https://github.com/oracle/helidon/issues/2205
  - [ ] About MP Health Checks specification
  - [ ] Concepts
  - [ ] Use cases
- [ ] JAX-RS/Jersey
  - [x] About JAX-RS specification and why it's supported
  - [ ] Concepts
  - [ ] Use cases
- [x] JPA/JTA https://github.com/oracle/helidon/issues/2201
  - [x] There is nothing currently here, but there is some HikariCP and JTA docs under Extensions  ---incl a new brief intro
  - [ ] How to access databases
  - [x] What is JPA
  - [ ] What is JTA
  - [ ] How to configure it
  - [ ] Use cases
- [ ] JWT Auth
  - [ ] About the specification
  - [ ] Concepts
  - [ ] Use cases
- [x] Metrics
  - [ ] About the specification
  - [ ] Concepts
  - [ ] Use cases
- [x] OpenAPI https://github.com/oracle/helidon/issues/2199
  - [ ] About the specification
  - [ ] Concepts
- [x] Reactive Messaging [1483](https://github.com/oracle/helidon/pull/1483)
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
- [x] Reactive Streams
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
- [ ] REST Client https://github.com/oracle/helidon/issues/2200
  - [ ] About the specification
  - [ ] Concepts
- [ ] Security
  - [ ] More use cases?
- [ ] Tracing [1979](https://github.com/oracle/helidon/issues/1979)
  - [ ] About the specification
  - [ ] Concepts
- [x] Websocket [1631](https://github.com/oracle/helidon/pull/1631) Santiago
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
- [x] Cross Origin Resource Sharing (CORS) support [1632](https://github.com/oracle/helidon/issues/1632)
**Additional Resources**

- [ ] Community opens in a new window

**Other**
- [x] How can I change title which is displayed at the top of each page. It displays Se instead of SE.
      LJ - Add h1Prefix: SE or MP to the front matter of your topic

**Comment by jagarcia14** [comment]
This is a great list!

I think two things would be helpful:

1. Let's develop an "over/under line" for the release; documents required for the release over, and those that can be added after the release under.

2. I am not familiar with the content, so every line in this list is equal with regard to effort and importance. Can we scope these topics in a bit more detail?

**Comment by ljamen** [comment]
@m0mus ,
I created separate issues for the items that I believe we can get to before the end of April. If there are other P1 (higher priority) items that you want us to attack first, let me know and I'll create tracking issues for those. Vanaja and I will need a dev resource for each item on the list.

**Comment by ljamen** [comment]
Added tracking issues for each outstanding task in this epic. Work on these issues to be completed for the next 2.0.x update.
