### ISSUE TITLE
Helidon CLI

### ISSUE THREAD

**Issue by spericas** [oracle/helidon#1544]
Work for next milestone:

- [x] Latest version resolution in init command (https://github.com/oracle/helidon-build-tools/issues/80)
- [X] Init command should support overriding of group and artifact ID
- [x] Init command should support a package option (https://github.com/oracle/helidon-build-tools/issues/100)
- [x] Helidon template harness (https://github.com/oracle/helidon-build-tools/issues/94)
- [X] Standalone binary (https://github.com/oracle/helidon-build-tools/issues/81)
- [x] Filter Maven output (https://github.com/oracle/helidon-build-tools/issues/93)
- [x] Syntax coloring (https://github.com/oracle/helidon-build-tools/issues/84)
- [x] Support for Helidon features (https://github.com/oracle/helidon-build-tools/issues/85)
