### ISSUE TITLE
Documentation Epic for Helidon 2.0 

### ISSUE THREAD

**Issue by ljamen** [oracle/helidon#1657]
This epic will be used to track the documentation tasks required for **Helidon 2.0** official release.

See [1515](https://github.com/oracle/helidon/issues/1515) for the complete list of documentation tasks for Helidon (not release specific). 

**About**
Writer: Lisa
Reviewers/SMEs: Dmitry, Joe, Tim, Tomas, Santiago, Romain
Status: In Review, see [1625](https://github.com/oracle/helidon/issues/1625)
- [x] Introduction to Helidon
  - [x] Helidon purpose in general
  - [x] Helidon goals
  - [x] More about 2 flavors of Helidon
  - [x] Differences between SE and MP
  - [x] Add updated links to new topics for 2.0
  - [x] Merged
**Pull Request**: [1625](https://github.com/ljamen/helidon/blob/docs_helidon_intro_1625/docs/about/02_introduction.adoc)

**SE**

- [x] **Introduction to Helidon SE 2.0**
Writer: Lisa
Reviewers/SMEs: Dmitry, Joe, Tim, Tomas, Santiago, Romain
Status: In Progress, see  [1626](https://github.com/oracle/helidon/issues/1626)
  - [x] Nice image with components (from slides) or cards
  - [x] Update components list, add links
  - [x] Merged
**Pull Request:** [1729](https://github.com/oracle/helidon/pull/1729)

- [x] **SE Config**
Writer: Tomas / Vanaja
Reviewers/SMEs: Tomas, Dmitry
Status: SE Config changes were merged, see [1420](https://github.com/oracle/helidon/issues/1420)
   - [ ] Reflect Helidon 2.0 changes 
Pull Request: 
Merged:

- [x] **DB Client** 
Writer: Lisa
Reviewers/SMEs: Tomas, Dmitry
Status: In Review, see [1629](https://github.com/oracle/helidon/issues/1629)
   - [x] Write docs (new in 2.0)
   - [x] Add updated link to new examples in Next Steps
  -  [ ] Merged
Pull Request: [1652](https://github.com/oracle/helidon/pull/1652)

- [x] **Reactive Messaging** 
Writer: Lisa
Reviewers/SMEs: Daniel
Status: Complete
Pull Request: [1483](https://github.com/oracle/helidon/pull/1483)
[x] Merged: Yes

- [x] **Reactive Streams**
Writer: Lisa
Reviewers/SMEs: Daniel
Status: ? Is this part of 1483 
  - [ ] Merged:

- [x] **Web Client** 
Writer: Vanaja
Reviewers/SMEs: David
Status: In progress, see (https://github.com/oracle/helidon/issues/1630)
  - [x] Write docs (new in 2.0)
  - [x] Merged
Status: In review
**Pull Request**: [1659](https://github.com/oracle/helidon/pull/1659) 

- [x] **Websocket** 
Writer: Santiago
Reviewers/SMEs: Dmitry, Joe 
Status: Complete
Pull Request:  [1631](https://github.com/oracle/helidon/pull/1631) 
[x] Merged: Yes Merged into Master

- [x] **Cross Origin Resource Sharing (CORS) SE support**
Writer: Barbara
Reviewers: Santiago, Tim
Status: In progress [1632](https://github.com/oracle/helidon/issues/1632)
Pull Request: 
Merged:

**MP**

- [x] **Introduction to Helidon MP 2.0** 
Writer: Lisa
Reviewers/SMEs: Dmitry, Joe
Status: In progress, see [1628](https://github.com/oracle/helidon/issues/1628)
  - [x] Nice image with components (from slides) or cards
  - [ ] Update components list, add links
Pull Request: [1653](https://github.com/oracle/helidon/pull/1653)
Merged:

- [ ] **MP Config** 
Writer: Vanaja
Reviewers/SMEs: Tomas
Status: In progress; need assistance from Tomas, see [1697](https://github.com/oracle/helidon/issues/1697)
  - [ ] About MP Config specification
  - [ ] Concepts
  - [ ] How it's related to Helidon SE Config (partially covered in JAX-RS)
  - [ ] Use cases 
Pull Request: 
Merged:

- [x] **Reactive Messaging** 
Writer: Lisa
Reviewers/SMEs: Daniel
Status: In progress, see [1483](https://github.com/oracle/helidon/pull/1483)
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
Pull Request: 
Merged:

- [x] **Reactive Streams**
Writer: Lisa
Reviewers/SMEs: Daniel
Status: 
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
Pull Request: 
Merged:

- [x] **Websocket** 
Writer: Santiago
Reviewers/SMEs: Joe, Dmitry
Status: Merged into Master, see [1631](https://github.com/oracle/helidon/pull/1631)  
  - [x] About the specification
  - [x] Concepts
  - [x] Use cases
Pull Request: 
Merged:

- [x] **Cross Origin Resource Sharing (CORS) MP support**
Writer: Barbara
Reviewers: Tim, Santiago
Status: In progress [1689](https://github.com/oracle/helidon/issues/1689)
 Pull Request: 
Merged:

**Comment by ljamen** [comment]
completed all doc tasks in this epic except for Config.
