### ISSUE TITLE
MicroProfile 3.3

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2147]
## Environment Details
* Helidon Version: 2.0.0
* Helidon MP

----------

## Problem Description
Upgrade MicroProfile support from 3.2 to 3.3. See specification at https://download.eclipse.org/microprofile/microprofile-3.3/microprofile-spec-3.3.html#microprofile3.3

Please verify the latest micro release for a given spec. The versions captured below were current at the time of this writing.

- [x] Config 1.4 (#1721)
- [x] Fault tolerance 2.1.1 (#2337)
- [x] Health 2.2 (#2259)
- [x] JWT Auth 1.1.1 (same as 3.2)
- [x] Metrics 2.3.2 (#2140)
- [x] Open API 1.1.2 (same as 3.2)
- [x] Open Tracing 1.3.3 (#2312)
- [x] Rest Client 1.4.1 (#2338)
- [x] Get MP Starter updated (#2372)
