### ISSUE TITLE
SE Fault Tolerance follow up

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2158]
## Environment Details
* Helidon Version: 2.x
* Helidon SE
----------

Follow up tasks:

- [ ] Configure defaults from config for each FT handler (currently only executor service configured)
- [ ] Add SE documentation for Fault Tolerance
- [ ] Wrap executor services with context (if explicitly configured)
- [ ] Use named handlers (as is done with `Bulkhead`) to allow nicer debugging, logs and metrics
- [ ] Add support for metrics

**Comment by spericas** [comment]
@tomas-langer Other than docs (in progress), do you see any of the other items in this checklist as must haves for 2.1.0? If so, could you elaborate more on those?
