### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2160]
Time to update some of our third party dependencies. 

High priority:

- [x] [Netty](https://netty.io/news/2020/07/09/4-1-51-Final.html) (PR #2204)
- [x] Hibernate (including plugin) (see issue #2080) (PR #2212)

Should also look at:

- [x] Jackson (maybe move to [2.11.x](https://medium.com/@cowtowncoder/jackson-2-11-features-40cdc1d2bdf3)?) (PR #2162)
- [x] Weld (PR #2176)
- [ ] Narayana

MicroProfile is covered by #2147

**Comment by barchetta** [comment]
This issue is out of date. We've done a couple rounds of dependency updates since it was created. Closing.
