### ISSUE TITLE
Helidon 1.x third party upgrades

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#2566]
We should upgrade the following third party components to match what is currently in Helidon 2 where appicable:

- [x] google-api-client  to 1.30.11 (2.x PR #2482) @barchetta 
- [x] snakeyaml to 1.27 (2.x PR #2482) @barchetta 
- [x] mysql-connector-java to 8.0.22 (2.x PR #2557) @Tomas-Kraus 
- [ ] ~~Weld to 3.1.4 (2.x PR #2177) @tomas-langer~~ We chose not to do this because it introduces Jakarta maven artifacts
- [x] Hibernate to 5.4.25.Final (2.x PR #2575) @ljnelson 
- [x] OCI SDK to 1.28.0 (2.x PR #2645) @ljnelson 
- [x]  guava to 30.0-jre (2.x PR #2620) @barchetta 
- [x] remove weld-probe-core (2.x PR #2506) @romain-grecourt 
- [x] apache-httpclient to 4.5.13 (2.x PR#2482) @barchetta 
- [x] grpc java 1.35.0 (2.x PR #2388) @thegridman 
- [x] eclipselink 2.7.5 (2.x PR #2138) @ljnelson 
- [x] Jacksion to 2.10.5, databind to 2.10.5.1
- [x] jersey from 2.29.1 to 2.33 (2.x PR #1438, #1887, #2406, #2727 ) @spericas 
- [x] GraalVM to 21.0.0 (2.x PRs #2514 #2510) (1.4.7 is at 19.2.0) @tomas-langer @barchetta 
- [x] Netty to 4.1.59.Final
