### ISSUE TITLE
TODO application does not work

### ISSUE THREAD

**Issue by romain-grecourt** [oracle/helidon#2707]
The TODO example application is not working (examples/todo-app), here is a description of the issues:

- [ ] The authentication configuration of the frontend is not used
- [ ] The regular expression for the paths to be secured is  `/api/[{*}]`, this is not recursive so the DELETE calls are failing
- [ ] In the past, all headers were propagated but it now requires explicit code or configuration, thus the `Authorization` header is not passed from the frontend calls to the backend.
- [ ] The current version of the Cassandra driver uses guava and the version it needs conflict with the version of guava used by the google login lib
- [ ] The K8S YAML files are using old version of Kubernetes APIs and do not work with the latest version available with docker for desktop.
