### ISSUE TITLE
Hashicorp Vault Integration

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#2966]
Epic for HCP Vault integration.

TODO:

- [ ] #2961 Add documentation
- [ ] #2962 Validate native image in MP
- [ ] #2963 Check and document integration with Tracing
- [ ] #2964 Check and document integration with HealthChecks (maybe add a health check for OCI?)
- [ ] #2965 Check and document integration with Metrics

DONE (#2895)
- Add CDI support for reactive interfaces, so this can be tested in an MP application
- Add blocking APIs + CDI support for injecting them
- Validate all modules exist in `bom/pom.xml`
- Add CDI examples
- Validate reactive examples work with native-image
- Update `FeatureCatalog` with the new modules
- Validate `module-info.java` exists for all modules (except for examples)
- Integration test using k8s authentication and database secrets with MySQL

**Comment by tomas-langer** [comment]
Closing this epic. The basic integration  is done, missing features are prioritized.
