### ISSUE TITLE
JPA Enhancements

### ISSUE THREAD

**Issue by ljnelson** [oracle/helidon#3008]
This epic is to track various JPA-related fixes and improvements.  The sub-tasks in this epic are in no particular order and are subject to change, deletion or augmentation without notice.

* [ ] Inflate container-managed `EntityManagerFactory` client proxies early so that such inflation does not occur during a JTA-managed transaction
* [ ] Maven plugin for auto-including entity classes in a `persistence.xml`
* [ ] Look at doing our own Eclipselink weaving plugin so we can avoid depending on [the one we're using](https://github.com/ethlo/eclipselink-maven-plugin) at the moment
* [ ] Make it easy to make `PersistenceUnitInfo` objects (they're already picked up if present as CDI beans but this is sort of a hidden feature at the moment)

**Comment by ljnelson** [comment]
Closed per request
