### ISSUE TITLE
Client MP Generator

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#4266]
MVP

- [x] Basic Generator (https://github.com/tjquinno/openapi-generator/pull/19)
- [x] Helidon Version support (based on common code)
- [x] Interface Support
- [x] Full Project
- [x] Serialization support (using `serializatonLibrary` with `jsonb` or `jackson` in `additionalProperties`)
- [ ] #4702 
- [x] Maven
- [x] #4703
- [x] #4704

Nice to Have

- Multipart
- Gradle

See:
#4126
#4025
#4116

**Comment by spericas** [comment]
Closing this epic since we have another issue #4702 to track missing security task.
