### ISSUE TITLE
OpenAPITool Test Framework

### ISSUE THREAD

**Issue by barchetta** [oracle/helidon#4267]
- [x] Determine general design/approach
- [x] Implement basic framework usable by Helidon client and server generators
- [x] Adopt and use in at least one generator

**Comment by spericas** [comment]
I believe this issue is now covered by a combination of unit and integration tests. Closing.
