### ISSUE TITLE
Deprecations: Metrics

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4365]
- MetricsSupport - 3 methods, replacing Conifg with metrics settings (no info)
- KeyPerformanceIndicatorMetricsSettings - New class in metrics API, this is for backward compatibility only (no info)
- RegistryFactory - New class in metrics API, this is for backward compatibility only (no info)

Tasks:
- [x] #4397 remove the deprecated code
- [x] #4396 make sure the deprecation is correctly documented in 2.x (since, forRemoval on @Deprecated annotation, use @deprecated javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist)
- [x] #4396 validate documentation and examples are correct with regard to the deprecated element
