### ISSUE TITLE
Deprecations: LRA

### ISSUE THREAD

**Issue by tomas-langer** [oracle/helidon#4368]
- CoordinatorClient - multiple methods (no info)
- Headers (no info about replacement or alternatives, or since)
 
Tasks:
- [ ] remove the deprecated code #4449
- [ ] make sure the deprecation is correctly documented in 2.x (since, forRemoval on @Deprecated annotation, use @deprecated javadoc tag to link to the correct new implementation, or describe what to do if a simple replacement does not exist) #4450
- [ ] validate documentation and examples are correct with regard to the deprecated element #4449
